name: AI-Assisted Development Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      max_iterations:
        description: 'Maximum number of iterations'
        default: '2'
        required: false
      force_continue:
        description: 'Force continue despite no changes'
        default: false
        type: boolean
permissions: write-all

env:
  MAX_ITERATIONS: ${{ github.event.inputs.max_iterations || '2' }}
  BRANCH_NAME: ${{ github.ref_name }}
  ITERATION_FILE: '.ai-iteration'

jobs:

  determine-iteration:
    runs-on: ubuntu-latest
    outputs:
      current_iteration: ${{ steps.get-iteration.outputs.iteration }}
      should_continue: ${{ steps.check-continue.outputs.should_continue }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get current iteration
        id: get-iteration
        run: |
          if [ -f $ITERATION_FILE ]; then
            ITERATION=$(cat $ITERATION_FILE)
          else
            ITERATION=1
          fi
          echo "iteration=$ITERATION" >> $GITHUB_OUTPUT
          echo "Current iteration: $ITERATION"
      
      - name: Check if we should continue
        id: check-continue
        run: |
          if [ "${{ github.event.inputs.force_continue }}" == "true" ]; then
            echo "should_continue=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if [ ${{ steps.get-iteration.outputs.iteration }} -ge $MAX_ITERATIONS ]; then
            echo "should_continue=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "should_continue=true" >> $GITHUB_OUTPUT

  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: eddie-rowe/ai-stylebot@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.tsx" # Optional: exclude patterns separated by commas


  trigger-next-iteration:
    needs: [determine-iteration, ai-review]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: villesau/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.tsx" # Optional: exclude patterns separated by commas